package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AddressInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ADDRESSINFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ADDRESSINFO_ID_GENERATOR", sequenceName = "ADDRESSINFO_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String city;

	private java.lang.String street;

	private java.lang.Integer streetNumber;

	private java.lang.String zipCode;

	public AddressInfo() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public java.lang.Integer getStreetNumber() {
		return this.streetNumber;
	}

	public void setStreetNumber(java.lang.Integer streetNumber) {
		this.streetNumber = streetNumber;
	}

	public java.lang.String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.String zipCode) {
		this.zipCode = zipCode;
	}

	public AddressInfo(java.lang.Long id, java.lang.String city,
			java.lang.String street, java.lang.Integer streetNumber,
			java.lang.String zipCode) {
		this.id = id;
		this.city = city;
		this.street = street;
		this.streetNumber = streetNumber;
		this.zipCode = zipCode;
	}

}