package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ConfirmDelivvery implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CONFIRMDELIVVERY_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CONFIRMDELIVVERY_ID_GENERATOR", sequenceName = "CONFIRMDELIVVERY_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String result;

	private java.lang.String description;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private com.poc_datamodel.poc_datamodel_v1.DeliveryInfo deliveryInfo;

	public ConfirmDelivvery() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public com.poc_datamodel.poc_datamodel_v1.DeliveryInfo getDeliveryInfo() {
		return this.deliveryInfo;
	}

	public void setDeliveryInfo(
			com.poc_datamodel.poc_datamodel_v1.DeliveryInfo deliveryInfo) {
		this.deliveryInfo = deliveryInfo;
	}

	public ConfirmDelivvery(java.lang.Long id, java.lang.String result,
			java.lang.String description,
			com.poc_datamodel.poc_datamodel_v1.DeliveryInfo deliveryInfo) {
		this.id = id;
		this.result = result;
		this.description = description;
		this.deliveryInfo = deliveryInfo;
	}

}