package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ConfirmScheduleDeliveryCallback implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CONFIRMSCHEDULEDELIVERYCALLBACK_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CONFIRMSCHEDULEDELIVERYCALLBACK_ID_GENERATOR", sequenceName = "CONFIRMSCHEDULEDELIVERYCALLBACK_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String result;

	private java.lang.String description;

	private java.lang.String correlationId;

	public ConfirmScheduleDeliveryCallback() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getCorrelationId() {
		return this.correlationId;
	}

	public void setCorrelationId(java.lang.String correlationId) {
		this.correlationId = correlationId;
	}

	public ConfirmScheduleDeliveryCallback(java.lang.Long id,
			java.lang.String result, java.lang.String description,
			java.lang.String correlationId) {
		this.id = id;
		this.result = result;
		this.description = description;
		this.correlationId = correlationId;
	}

}