package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CustomerInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CUSTOMERINFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CUSTOMERINFO_ID_GENERATOR", sequenceName = "CUSTOMERINFO_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	private java.lang.String surname;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private com.poc_datamodel.poc_datamodel_v1.AddressInfo address;

	private java.lang.String customerType;

	private java.lang.Boolean badPayer;

	public CustomerInfo() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public com.poc_datamodel.poc_datamodel_v1.AddressInfo getAddress() {
		return this.address;
	}

	public void setAddress(
			com.poc_datamodel.poc_datamodel_v1.AddressInfo address) {
		this.address = address;
	}

	public java.lang.String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(java.lang.String customerType) {
		this.customerType = customerType;
	}

	public java.lang.Boolean getBadPayer() {
		return this.badPayer;
	}

	public void setBadPayer(java.lang.Boolean badPayer) {
		this.badPayer = badPayer;
	}

	public CustomerInfo(java.lang.Long id, java.lang.String name,
			java.lang.String surname,
			com.poc_datamodel.poc_datamodel_v1.AddressInfo address,
			java.lang.String customerType, java.lang.Boolean badPayer) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.address = address;
		this.customerType = customerType;
		this.badPayer = badPayer;
	}

}