package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DeliveryInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DELIVERYINFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "DELIVERYINFO_ID_GENERATOR", sequenceName = "DELIVERYINFO_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String date;

	private java.lang.Boolean signed;

	public DeliveryInfo() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.Boolean getSigned() {
		return this.signed;
	}

	public void setSigned(java.lang.Boolean signed) {
		this.signed = signed;
	}

	public DeliveryInfo(java.lang.Long id, java.lang.String date,
			java.lang.Boolean signed) {
		this.id = id;
		this.date = date;
		this.signed = signed;
	}

}