package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class InDelivery implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INDELIVERY_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "INDELIVERY_ID_GENERATOR", sequenceName = "INDELIVERY_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String orderId;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private com.poc_datamodel.poc_datamodel_v1.CustomerInfo customer;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private com.poc_datamodel.poc_datamodel_v1.DeliveryAppointment deliveryAppointment;

	public InDelivery() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.String orderId) {
		this.orderId = orderId;
	}

	public com.poc_datamodel.poc_datamodel_v1.CustomerInfo getCustomer() {
		return this.customer;
	}

	public void setCustomer(
			com.poc_datamodel.poc_datamodel_v1.CustomerInfo customer) {
		this.customer = customer;
	}

	public com.poc_datamodel.poc_datamodel_v1.DeliveryAppointment getDeliveryAppointment() {
		return this.deliveryAppointment;
	}

	public void setDeliveryAppointment(
			com.poc_datamodel.poc_datamodel_v1.DeliveryAppointment deliveryAppointment) {
		this.deliveryAppointment = deliveryAppointment;
	}

	public InDelivery(
			java.lang.Long id,
			java.lang.String orderId,
			com.poc_datamodel.poc_datamodel_v1.CustomerInfo customer,
			com.poc_datamodel.poc_datamodel_v1.DeliveryAppointment deliveryAppointment) {
		this.id = id;
		this.orderId = orderId;
		this.customer = customer;
		this.deliveryAppointment = deliveryAppointment;
	}

}