package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ScheduleDelivery implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SCHEDULEDELIVERY_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SCHEDULEDELIVERY_ID_GENERATOR", sequenceName = "SCHEDULEDELIVERY_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private com.poc_datamodel.poc_datamodel_v1.CustomerInfo customer;

	private java.lang.String contactType;

	public ScheduleDelivery() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public com.poc_datamodel.poc_datamodel_v1.CustomerInfo getCustomer() {
		return this.customer;
	}

	public void setCustomer(
			com.poc_datamodel.poc_datamodel_v1.CustomerInfo customer) {
		this.customer = customer;
	}

	public java.lang.String getContactType() {
		return this.contactType;
	}

	public void setContactType(java.lang.String contactType) {
		this.contactType = contactType;
	}

	public ScheduleDelivery(java.lang.Long id,
			com.poc_datamodel.poc_datamodel_v1.CustomerInfo customer,
			java.lang.String contactType) {
		this.id = id;
		this.customer = customer;
		this.contactType = contactType;
	}

}