package com.poc_datamodel.poc_datamodel_v1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class StartDeliveryProcess implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "STARTDELIVERYPROCESS_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "STARTDELIVERYPROCESS_ID_GENERATOR", sequenceName = "STARTDELIVERYPROCESS_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String orderId;

	private java.lang.String customerId;

	public StartDeliveryProcess() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.String orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public StartDeliveryProcess(java.lang.Long id, java.lang.String orderId,
			java.lang.String customerId) {
		this.id = id;
		this.orderId = orderId;
		this.customerId = customerId;
	}

}